#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
/usr/local/lsf/etc/job_starter 'export PRODHOME=/afs/cern.ch/work/s/schoef/CMS/gen/gridpacks; gridpack_generation.sh ttZ0j_rwgt addons/cards/ttZ0j_rwgt 8nh  '
ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
